### ISSUE TITLE
3D rotation with mouse

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#10]
Please add the ability to rotate camera in 3D while holding a right mouse button (like holding a SPACE currently works). That keyboard using for 3D navigation is just the most lame thing in all Hammer clones.

**Comment by Duude92** [comment]
Do we ever need this feature since there are camera movement with SPACE or Z button?
It might have some conflicts with RMB context menu in 3D view.

**Comment by Qwertyus3D** [comment]
No conflicts, I think, the context menu does not even appear anyways if you holding an RMB. It only appears on fast RMB click. I'd like to have full camera rotation with mouse and leave keyboard keys for camera moving. This approach works perfectly in BSPGuy, for example.

**Comment by Qwertyus3D** [comment]
It allows to move camera and select/manipulate objects much more easy.

**Comment by Duude92** [comment]
Added support of Mouse Look by holding middle mouse button, because part of code that used to rotate camera - uses RMB and LMB to calculate camera movement.
Pushed into the **latest** release

**Comment by Qwertyus3D** [comment]
Well, thanks! Not exactly what I wanted, but better, than with keyboard.
