### ISSUE TITLE
Reopen latest file option

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#14]
I see editor just uses this by default, without any settings. It also opens previous file even if I open another map file by double-clicking (by file associations). So it loads 2 files instead of 1.

**Comment by Duude92** [comment]
There is some issues with multiple tabs as I see. I'll add setting to disable 'Reopen latest files' option.

**Comment by Duude92** [comment]
Option is placed in "Autosaving"->"Open latest documents on startup"

**Comment by Qwertyus3D** [comment]
Nice, thanks.
