### ISSUE TITLE
[FEATURE REQUEST] Origin editing

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#19]
Simple, as it sounds. Add the editable "Origin" field for entities (Property name / Value in "Object properties" window). Currently it's not possible to view/edit it manualy, though it's a basic parameter of any entity.

**Comment by Duude92** [comment]
Are you confused by Source Engine?
Hammertime currently doesn't support Source Engine modifications, nor Source FGD file structure.
For GoldSrc: compilers decides where origin is - by placing solid brush with 'origin' texture groupped with entity.
If you modding some GoldSrc game, that requires their own map compilers - then they probably should provide right FGD, that contain Object Origin field.

**Comment by Qwertyus3D** [comment]
I want to edit a position of point entities on map manually. If you open a saved map file, you see origin for any entity, like this:
```
{
"classname" "weapon_9mmhandgun"
"delay" "0"
"angles" "0 0 0"
"target" "gun_mm"
"origin" "1709.65 3349.94 80.0647"
}
```
So origin I'm talking about is not a compiler related thing and not about any special mod. FDGs normally don't have origin field. A I have no idea how to add it. And why if map editor could just show this field by default, at least in Smart Edit mode.

**Comment by Qwertyus3D** [comment]
Thanks, it works. But has problems with Undo/Redo. Doesn't show changes. Also sometimes edited object just disappers (probably can caused by editing more than 1 value at once..

**Comment by Duude92** [comment]
Updated code, now it supports undo/redo actions.
Need more information about second issue - can't reproduce it rn.

**Comment by Duude92** [comment]
What about this feature, does issue with disappearing object stil remains?

**Comment by Qwertyus3D** [comment]
I downloaded latest build, it doesn't have Origin feature at all. Shoud I revert to previous build to test?

**Comment by Duude92** [comment]
To test function - download from [latest-origin-editing-feature](https://github.com/Duude92/hammertime/releases/tag/latest-origin-editing-feature) release, since that feature could cause new bugs - I wont merge feature branch into development one

**Comment by Qwertyus3D** [comment]
Seems to be working as intended, at least see no conflicts with anything.
