### ISSUE TITLE
[BUG] Copy/paste does not work?

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#22]
Trying to copy/paste any entity/brush, but doesn't work at all.

**Comment by Qwertyus3D** [comment]
The issue seems to be happen with interface buttons. Shortcus are working.

**Comment by Duude92** [comment]
Are you talking about 3D view?

**Comment by Qwertyus3D** [comment]
Yes, probably

**Comment by Duude92** [comment]
Fix with 5d314d0 in #1, please review and report if bug is still remain. If so - please provide more info.

**Comment by Qwertyus3D** [comment]
"Paste" toolbar button still doesn't work. Nor in 3D, nor in 2D.

**Comment by Duude92** [comment]
Aww, the toolbar button
fix with 491b788

**Comment by Qwertyus3D** [comment]
Loks like working now, thanks.
