### ISSUE TITLE
[BUG] Zoom out does not center view on mouse cursor

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#23]
The view is getting adjusted (centered) to mouse cursor position in 2D viewports only on zooming in, zooming out ingnores mouse cursor, making it hard to adjust view.

**Comment by Duude92** [comment]
Can you provide more information, since I cannot reproduce that bug?
[Check out this video](https://www.youtube.com/watch?v=CRR0EIpbzb4)

**Comment by Qwertyus3D** [comment]
Well, maybe I just do not get how to use it effectively :). Anyways using middle mouse button to drag a view seems to be a good way to solve it.
