### ISSUE TITLE
[FEATURE REQUEST] Remember export format

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#24]
After using "Export" feature, remember the type of map format used to export for the next time. Or make it possible to select preferred map format for export instead.

Maybe make it work for "Save as" too.

**Comment by Duude92** [comment]
With 3e49407 added feature to store last chosen extension in #1.
Please report if it's working as intended.

**Comment by Qwertyus3D** [comment]
Seems to be working. But no deep testing.
