### ISSUE TITLE
[FEATURE REQUEST] Make it remember last used grid setting

### ISSUE THREAD

**Issue by Qwertyus3D** [Duude92/hammertime#27]
Every time on editor's start the grid setting gets reset to "default" value. Would be nice to save last used user choice instead.

**Comment by Duude92** [comment]
I'm not sure how to implement this.
I would implement "default grid size" for environment - no problem.
Last used value. I can save it, but it would be applied to every environment/every document.
Best way to store it for each map individually, but specifications for rmf/map formats doesn't include grid size.
Any suggestion?

**Comment by Duude92** [comment]
I've added default grid size property to Environment editor, that would set its value to newely created document or opened with selected environment. You can set for every environment its own default value.
Its should be in its default range [0.25 - 1024] and should be exponent value 2^value to draw grid properly
![image](https://github.com/Duude92/hammertime/assets/11941696/2804e5a0-eb32-4af7-81fa-bcd879492dfc)

**Comment by Qwertyus3D** [comment]
Nice, seems to be good enough. Thanks!
